### ISSUE TITLE
weird link spam on user profile pages

### ISSUE THREAD

**Issue by Mumberthrax** [travis-g/Voat-Enhancement-Suite#32]
viewing any user profile page with VES enabled shows five hyperlinks labeled "VES" directing to http://github.com/travis-g/Voat-Enhancement-Suite, all in one general area of the page - one above the trophies and badges section, two in the trophies and badges section, and two at the bottom of the list of moderated subverses.

**Comment by travis-g** [comment]
That's actually hilarious...
