### ISSUE TITLE
Chrome doesn't like version number for extension

### ISSUE THREAD

**Issue by deepdesigns6** [travis-g/Voat-Enhancement-Suite#43]
I pull the version number from the package info. It didn't like adding ~alpha. Can we put the build tag in a different spot?

**Comment by travis-g** [comment]
I thought I responded to this earlier...would setting the version as 0.0.4a work? If not I'll find a way to designate the untested alphas.

**Comment by travis-g** [comment]
Does a version string of '0.0.4a' solve this?

[Version string in package.json](https://github.com/travis-g/Voat-Enhancement-Suite/blob/040deb0b61139c814ff72c98f20a0ce375c070ea/package.json#L9)

**Comment by deepdesigns6** [comment]
There is version and version name. Only numbers in version, version name can be alphanumeric. See:

https://developer.chrome.com/extensions/manifest/version

How has voat been for you? It's been impossible for me lately!

**Comment by travis-g** [comment]
Ahh, I'll take a look. 

Voat's been up for me maybe 70% of the time overall, but when I'm actually able to work it's rarely up. It's getting slowly more reliable now that CloudFlare is up.
