### ISSUE TITLE
proper attribution to Reddit Enhancement Suite would be appreciated, and GPLv3 licensing would be ideal.

### ISSUE THREAD

**Issue by honestbleeps** [travis-g/Voat-Enhancement-Suite#44]
While it's clear that you've obviously done a lot of work on your own, the style and a great deal of the code for VES is copied / pasted directly from RES.

RES is open source and GPLv3, which means that you're perfectly free to modify it, to distribute it - heck, you can even sell your variant for money and I give you permission. 

You're technically required, however, to:

- license your derivative as GPLv3
- include our copyright notice(s)
- [a variety of other stuff comes with this license](https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3))

You technically don't have the right to release this as "DWTFYW" - which is a perfectly lovely license, but is not GPLv3 compatible.

[reddit enhancement suite's license.txt](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/master/LICENSE)

[current VES license.txt](https://github.com/travis-g/Voat-Enhancement-Suite/blob/817d7f593d68f4444b0b7d6b5ffcbc5fd4cbb363/LICENSE)

[source code from Reddit Enhancement Suite's console](https://github.com/honestbleeps/Reddit-Enhancement-Suite/blob/01923f7d49309e3f7392f7e5a5e501bf6afdddd1/lib/core/options.js#L118) 

[very clearly copy-pasta'ed code in VES](https://github.com/travis-g/Voat-Enhancement-Suite/blob/b4e4c8e1443fe27d6a329dae8fb29854bb41ee28/src/core/options.js) 

The fact that you went to the trouble of copy/pasting RES's code, but stripped the license from it and then went and edited our comments and attribution to us etc is mildly disappointing.  I'm not even necessarily asking that you GPLv3 your code (though technically you are obligated to) - but taking away attribution when you've very clearly copied and pasted my code is impolite. You had to go to extra effort to not attribute the authors of RES here.

**Comment by travis-g** [comment]
[The WTFPLv2 is GPLv3 compatible.](http://www.gnu.org/licenses/license-list.en.html#GPLCompatibleLicenses) The term "compatible" is where my confusion stemmed from, so my apologies.

Certain assertions you have made do not holistically capture the circumstances, but are understandable nonetheless. Attribution and a relicense will be completed quickly to hopefully prevent any further bad blood toward me as a developer.

Again, I apologize for my mistakes.

**Comment by honestbleeps** [comment]
Thank you for understanding. I certainly don't mind people using our work - that's why it's open sourced and licensed the way it is.  I just feel that, at the very least, the courtesy of attributing who the work was derived from is a reasonable minimum expectation.

I appreciate your response, thanks again.
